server {
    listen 80;
    listen [::]:80;
    server_name feedback.samdpi.uz www.feedback.samdpi.uz;

    location = /favicon.ico {
        access_log off; log_not_found off;
    }
    location /static/ {
        root /home/ali/feedback/;
    }

    location /media/ {
        root /home/ali/feedback/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/feedback.sock;
    }
}