# Generated by Django 6.0.6 on 2026-06-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('bad', 'Yomon'), ('good', 'Yaxshi'), ('best', "A'lo")], max_length=100),
        ),
    ]
